import type { NextPage } from 'next'
import Head from 'next/head'
import { Tabs, Tab } from 'react-bootstrap'
import Button from 'react-bootstrap/Button'
import { LinhaTop } from '../components/LinhaTop'
import Header from '../components/header'
import { ContentCarrousel } from '../components/ContentCarrousel'
import { ItemNoticia } from '../components/ItemNoticia'
import { TitulosSecoes } from '../components/TitulosSecoes'
import { useEffect, useState } from 'react'
import { CarrouselImagens } from '../components/CarrouselImagens'
import { ItemAtende } from '../components/ItemAtende'
import { Footer } from '../components/Footer'
import { ItemButton } from '../components/ItemButton'
import { loadNoticias } from '../graphql/loadnoticias'
const SobrePage = () => {
  const [isLoading, setLoading] = useState(false)
  function simulateNetworkRequest() {
    return new Promise((resolve) => setTimeout(resolve, 2000))
  }

  const handleClick = () => setLoading(true)
  return (
    <>
      <Head>
        <title>Prefeitura Municpal de Manacapuru</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container noticiasSecao">
        <div className="row">
          <TitulosSecoes>Sobre</TitulosSecoes>
        </div>
        <div className="row">sobre</div>

        <div className="row linhabanners"></div>
      </div>
    </>
  )
}

export default SobrePage

export async function getServerSideProps() {
  const noticiaRes = await fetch(`${process.env.url}/api/noticias?populate=*`)
  const noticias = await noticiaRes.json()

  return {
    props: {
      noticias,
    },
  }
}
